# Generated by Django 2.2.1 on 2019-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
